import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <ul>
          <Link href='/' legacyBehavior><a style={{textDecoration:"none", color:'black'}}><li>Home</li></a></Link>
          <Link href='/contact' legacyBehavior><a style={{textDecoration:"none", color:'black'}}><li>Contact</li></a></Link>
          <Link href='/about' legacyBehavior><a style={{textDecoration:"none", color:'black'}}><li>About</li></a></Link>
        </ul>
      </nav>

      <div className={styles.main_heading}>
        <h1>Hunting Coder</h1>
        <p>A blog app by hunting coder for hunting coders</p>
      </div>

      <div className={styles.blogs}>
        <div className={styles.blog}>
          <h2>This is blog Title</h2>
          <p>Few content of blog.....</p>
        </div>
        <div className={styles.blog}>
          <h2>This is blog Title</h2>
          <p>Few content of blog.....</p>
        </div>
        <div className={styles.blog}>
          <h2>This is blog Title</h2>
          <p>Few content of blog.....</p>
        </div>
      </div>


      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
              By <Image src="/vercel.svg" alt="Vercel Logo" className={styles.vercelLogo} width={100} height={24} priority />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className="blogs">
            <div className="blogItem">
              <h1>Learn JS</h1>
              <p>Javascript is used to design logic for web</p>
            </div>
            <div className="blogItem">
              <h1>Learn JS</h1>
              <p>Javascript is used to design logic for web</p>
            </div>
            <div className="blogItem">
              <h1>Learn JS</h1>
              <p>Javascript is used to design logic for web</p>
            </div>
          </div>
          <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />

          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Find in-depth information about Next.js features and&nbsp;API.</p>
          </a>

          <a href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
          </a>

          <a href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Discover and deploy boilerplate example Next.js&nbsp;projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
          </a>
        </div>
      </main> */}
    </>
  );
}
